### ISSUE TITLE
Express TC Meeting - 2016-03-01

### ISSUE THREAD

**Issue by jasnell** [expressjs/discussions#1]
# Who

Invited: 
- @expressjs/express-tc 
- @mikeal (tsc mentor)
- @jasnell (tsc mentor) 
- @wesleytodd (observer)
- @tunniclm (observer)
- @hacksparrow (observer)
# When

March 1st, 2016 - 6:30pm Eastern (3:30pm Pacific)
# Where

Google Hangouts:

Link for Participants: https://plus.google.com/hangouts/_/hoaevent/AP36tYezJItkc6q3Z1E9wEw3Sp8uoxus30-oBznf8_hyZRAL3d6UnQ?hl=en&authuser=0

Link for Observers: https://plus.google.com/events/c1t25h6931767e8s357iuo2jclk
# Minutes

Google Doc: https://docs.google.com/document/d/1KZPRK4XnKhpVqFaQ_BjJmDxFHEm8N1xaEUfQvKLtG0E/edit
(please request access for editing)
# Agenda
- Bootstrapping the TC
- Process Discussion
- Release Team / Process
- Express JS Website - https://github.com/expressjs/express/issues/2902

**Comment by Fishrock123** [comment]
I think for now it should also be open for others who want to join as non-voters (not that we will have votes anyways but)

**Comment by jasnell** [comment]
Yep, I've asked @tunniclm and @hacksparrow to join in on the call. With hangouts we're limited to 15 so we still have plenty of room to have others join in. Feel free to add anyone else to the invited list.

**Comment by dougwilson** [comment]
What is the end time for the meeting? I don't see it listed anywhere, so cannot truely commit to attend without knowing a critical aspect of the meeting: the length/end time.

**Comment by jasnell** [comment]
Ah sorry, Node core calls are typically an hour. I didn't want to put an
end time on this one because I know there's quite a bit too discuss but we
should be able to good progress in an hour.

**Comment by cdnadmin** [comment]
Hey, guys, 

If it helps some, I would like to humbly recommend a hack.summit() 2016, youtube video with Rod Vagg, where he goes over the open source governance model, currently being used for Node.  

The video’s [here](https://youtu.be/ns6uC_9J4tU?t=1s). 

Quick vid-time references: 

- at about 29 mins and 35 secs, Rod talks about open governance in general (direct reference [here](https://youtu.be/ns6uC_9J4tU?t=29m35s) )
- at about 32 mins and 08 secs, he goes over the project structure: TSC, CTC, Collaborators, and Working Groups.   [vid ref](https://youtu.be/ns6uC_9J4tU?t=32m8s)
- at about 33 mins 15 secs, shows a nice venn diagram visualizing the Node.js Foundation structure, part of which is the Express Incubator Project.  [vid ref](https://youtu.be/ns6uC_9J4tU?t=33m15s)
- Rod finishes up going over:
   - philosophies, leadership, and guidelines
   - details over TSC, CTC, Collaborators, and Work Groups

--Monico

**Comment by thefourtheye** [comment]
Meeting time in local time http://m.wolframalpha.com/input/?i=March+1st%2C+2016+-+6%3A30pm+Eastern+in+local+time&x=0&y=0

**Comment by mikeal** [comment]
Just got a call from James. He won't be able to start the hangout on air because he'll be driving so I'm going to set it up. The good news is that we can use the Node.js G+ pages and youtube channel :)

New links are below:

* Public Stream: http://www.youtube.com/watch?v=vk2NfCzF8eg
* Hangout for Participants: https://plus.google.com/hangouts/_/hoaevent/AP36tYc50zJmYVZ0T0P1fXlG7HuNbQfOTfSB23wqcJzhCqmUu89CYg?eid=100598160817214911030&hl=en-GB&authuser=0

**Comment by Fishrock123** [comment]
@mikeal @jasnell This is supposed to be on Wednesdays (tomorrow) was the short month (February) not accounted for?

**Comment by jasnell** [comment]
Nope, just wasn't aware that a set day had been selected. I scheduled this
on Thursday last week. If necessary this can be moved.

**Comment by Fishrock123** [comment]
See the doodle link at https://github.com/expressjs/express/issues/2885#issuecomment-187263808 -- I think you filled it out too?

**Comment by jasnell** [comment]
Well yes, I'm aware of the doodle, wasn't aware that a set day of the week
had been selected. I set this to make sure something firm was in the
calendar. Feel free to reschedule.

**Comment by dougwilson** [comment]
Oh, no, Jeremiah. Do we think we can still have the meeting tonight? I'm absolutely available and anxious to actually have this TC meeting :) If we really have to we can reschedule for tomorrow, but I'm not sure if everyone can attend with only 1 day notice? I'm sure even the meeting tonight can still be productive?

**Comment by mikeal** [comment]
Someone should tell me if I'm doing this hangout or not ;)

**Comment by hacksparrow** [comment]
So, are we meeting? It's 4:00 am here.

**Comment by dougwilson** [comment]
> Someone should tell me if I'm doing this hangout or not ;)

I'll be there, or at least having a random group thing on hangouts like last week if no one can start this one.

**Comment by jasnell** [comment]
I'd prefer to keep this today, just to keep things moving. The regular
meeting can be on Wednesdays if that works best.

**Comment by hacksparrow** [comment]
I am on the hangout created by Mikeal. Anyone joining?

**Comment by blakeembrey** [comment]
Isn't it an hour away?

**Comment by jasnell** [comment]
It is scheduled for 3:30 Pacific, which is in one more hour. It's only 2:30
Pacific currently.

**Comment by dougwilson** [comment]
Unless I'm missing something, it doesn't start for one more hour (6:30pm Eastern).

**Comment by tunniclm** [comment]
I thought is was in 1 hours time as well.

**Comment by mikeal** [comment]
Ok, I'll plan on starting this at 3:30 PT.

**Comment by Fishrock123** [comment]
This is now at the exact time as another meeting I have.

**Comment by hacksparrow** [comment]
Looks like I missed something, see you guys at 3:30 pm PT.

**Comment by wesleytodd** [comment]
@mikeal This may be a silly question, but by posting the "participants" link, doesn't that mean anyone who clicks it can join the call?  Seems like this opens it up to, for lack of a better term, "randos" joining the call from this thread?  I just clicked it and was able to join the call.  Maybe this doesn't matter, but it seems like making a new one and not posting the link might be a good idea if you care about that...?

Secondly, since I am listed as an observer, does that mean you would like me to join on the participants call?  Now that you have it setup to stream to youtube my services are no longer needed for the public viewing :(  So not that I don't want to participate, but if the intent is not to have us "observers" talk then it might just be better if we watch from the live stream, no?

**Comment by mikeal** [comment]
@wesleytodd it's certainly possible that randos could show up but we've posted these many times prior and it hasn't been a problem. If it becomes a problem we'll stop sharing the participant link.

**Comment by wesleytodd** [comment]
Ok, thats good :)  I am used to a much more trollish internet and just err on the side of caution.  I would still appreciate some insight to the second question.  I have never watched one of these for node core, so I guess I am just a bit out of the look on how they work.

**Comment by mikeal** [comment]
@wesleytodd I'm not the right person to ask who should and should not be on the participant call. I'm only here to facilitate, I'll leave stuff like this to the express contributors.

**Comment by dougwilson** [comment]
I have no opinion, Wes :) I would say if you're on the list, even as an observer, feel free to join the participant link. I don't think observer really means you can't talk, I think it is more about any voting(?). Regardless, we are figuring it out still, so we'll see what works in the end.

**Comment by wesleytodd** [comment]
awesome, thanks @dougwilson!  I will hop on in a bit then, and hopefully I can constructively participate in some way.

**Comment by Fishrock123** [comment]
So long as we constructively get through any agenda, there isn't a problem with observers listening / contributing to discussion.

**Comment by mikeal** [comment]
> I don't think observer really means you can't talk, I think it is more about any voting(?)

In the context of other committees, working groups and TCs in the foundation "observer" has meant "active participant w/o voting privileges."

**Comment by dougwilson** [comment]
Thanks for attending the TC meeting today everyone! A new issue will be opened for the next meeting, but it should be scheduled for Wednesday, March 9th, 6:30pm Eastern.

In summary from the meeting, a couple points were agreed upon as actual action items to be done after this meeting:

1. The new contributor policy (https://github.com/expressjs/express/commit/f3d99a4fdbe1531ea609e92c4d4ae6c269d78c7a) has been adopted and will be applied to the three organizations in the Express.js project (pillarjs, jshttp, and expressjs) to identify the current committers to bootstrap a committer list for Express.js from. This new committer list will also be the initial Express.js TC, where the adjustment of the TC will proceed forward according to the contributor guide from that point forward. (https://github.com/expressjs/express/issues/2919)

2. The Express.js 4.x API documentation contributed into this organization will be coordinated with the expressjs.com website in order to de-duplicate the content between the two. An intermediate expressjs.info domain will be used as part of this process. (https://github.com/expressjs/express-api-docs/issues/2)

**Comment by gireeshpunathil** [comment]
meeting happened long back, closing. Please re-open if anything is outstanding here.
