### ISSUE TITLE
Express TC Meeting 03-05-2020

### ISSUE THREAD

**Issue by jonchurch** [expressjs/discussions#106]
## Attendance

The entire community is welcome to tune in and observe the meeting live at the time below. The following people are listed here as explicit invitees to get an email notification about the upcoming meeting:

Invited:

@expressjs/express-tc
@expressjs/triagers

Please use the following emoji reactions in this post to indicate your
availability.

* :+1: - Attending
* :-1: - Not attending
* :confused: - Not sure yet

## When
March 5, 2020 - 4:00 pm GMT 
[See it in your timezone](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Express+TC+Meeting&iso=20200305T16&p1=1440)

## Where
**Watch the recording:** TK
Zoom https://zoom.us/j/570940962

* Viewers: https://www.youtube.com/watch?v=dc2DC3X8D5A
* Participants: 

## Agenda

Document and make official repo captains #98
Followup on [plans from last meeting](https://github.com/expressjs/express/pull/2237#issuecomment-570058548)

> Just wanted to get this created, please feel free to edit

**Comment by jonchurch** [comment]
It was requested that folks review the [Repo Captains proposal](https://github.com/expressjs/discussions/issues/98) prior to the meeting, as it will be the first topic discussed

**Comment by ghinks** [comment]
I'll be there Jon.

**Comment by wesleytodd** [comment]
@dougwilson Let me know when you want to tackle getting the streaming setup right.  We have a few things to do:

1. Get your LastPass account setup
2. Get the OpenJSF to share the password with you
3. Convert the Express youtube channel to a shared account
4. Add those credentials to the last pass and ensure that someone from the foundation is also on that credential as an admin

@brianwarner, do you who on the foundation side we should share the new Express YT account credential with, is it you?

**Comment by brianwarner** [comment]
@wesleytodd and @dougwilson - In this case, the only credentials to share are for Zoom, so that you can log in as host and kick off live streaming.

For YouTube, we don't share credentials.  Instead, you add accounts as manager or owners.  Please feel free to share with me (bwarner@linuxfoundation.org) as an Owner, and that way I can escrow the ownership and add people if they need it.

In general, anybody who will kick off a live stream just needs to be a manager.

Make sense?

**Comment by dougwilson** [comment]
@wesleytodd for number 4 (the YouTube channel) I am 100% on board but I just don't know how to do that and need some kind of instructions. The only method I know if needs a phone number. See https://github.com/expressjs/discussions/issues/94

**Comment by wesleytodd** [comment]
@brianwarner The goal, as you say, is that someone on the foundation also has access to the YT credentials in case of an emergency.  And I already have the zoom credentials, we just need @dougwilson to also have them shared with him on whichever email he registers with LastPass on.

For the YT account, is there a foundation phone number we can use on the account?  I am happy to offer up my number if we need it, but I agree it would be better to use a shared one instead of one of our personal numbers.

**Comment by brianwarner** [comment]
I ran up against this with other YouTube accounts... I've verified as many as I can before my own timer resets (two per number per year).  Are you able to verify it with yours?  Otherwise, I'm not sure when I get to start verifying again.

**Comment by wesleytodd** [comment]
@dougwilson Do you have time tonight to work this out?  At least before tomorrow morning can we get the new google account created and the account shifted over?  Like I said, I am happy to use my personal phone as a stop gap.

**Comment by dougwilson** [comment]
Yep, I definitely do. Let's coordinate on our Lastpass email chain, especially if we need to pass not super public information back and forth :)

**Comment by LinusU** [comment]
I'm getting a "Webinar has expired." error when trying the link 🤔

**Comment by wesleytodd** [comment]
Let me see about starting it.  I think Doug might not be able to attend, but we can go at it for now, but it still means that it wont be streamed.  Here is the new link: https://zoom.us/j/570940962

**Comment by ghinks** [comment]
the zoom link above has expired

**Comment by wesleytodd** [comment]
I just updated the new link.  I think that above one was an accidental copy from last week.

**Comment by jonchurch** [comment]
https://github.com/expressjs/expressjs.com/pull/1114

**Comment by jonchurch** [comment]
@wesleytodd Please post the notes when you can

**Comment by wesleytodd** [comment]
- Next steps on repo captians
  - refine language and merge
  - Volunteers for repo captians:
    - @wesleytodd for `router` and `generator`
    - @gireeshpunathil & @ghinks for `session`
    - @LinusU [`api-error-handler`](https://github.com/expressjs/api-error-handler) (add to statusboard)
    - @jonchurch `expressjs.com`


| item name | tracking issue | owner | challenge/support required | eta |
|-------------|----------------|-------|----------------------------|-----|
| Change default setting of query parser  | #3621  | @gireeshpunathil & @HarshithaKP  |  | 2 weeks |
| Extracting req/res | #2432 | @wesleytodd | I need publish on @pillarjs | 2 weeks out |
| Status `undefined`  | #2795 #2797 #3111 #3137 #3143 | @jonchurch  |  | 1 week |
| Router 2.0 | pillarjs/router#42 https://github.com/expressjs/expressjs.com/pull/1114/files | @dougwilson @HarshithaKP | | 1 week |
| Remove the alpha tag on the 5.0 docs |  | @gireeshpunathil | | 1 week |

**Comment by wesleytodd** [comment]
My computer is processing the video now, I will post it so we can upload to YT asap.

**Comment by dougwilson** [comment]
> Extracting req/res

Didn't we specifically say we were not going to add anything more into the Express 5 release, including that specific item?

**Comment by dougwilson** [comment]
> Volunteers for repo captians

Do we want to add that into the issue #98 as well? I was actually about to type some stuff out here, but realized that it may be better to keep in that issue / wait until I had a chance to listen to the meeting, lol, so I'm not asking things that were already discussed in the meeting that I can just listen to.

**Comment by LinusU** [comment]
> Didn't we specifically say we were not going to add anything more into the Express 5 release

Oh, I thought we said that any other items from the original list would be nice to get in, but not a requirement for releasing 5.x.

I sent a PR for another item from that list here:  pillarjs/send#192

Totally understand if we should focus on getting the release out and not add anything more at the moment though.

That being said, @wesleytodd made a great argument for why we should get the "Exctract req/res" item in to the 5.x release: Since projects in the wild are doing deep requires into Express (e.g. `require('express/lib/request')`) this will be a breaking change since that will stop working; and if we don't lift them out it will make it harder to work on HTTP 2 and other extra protocol support, since most of that work would happen in the req/res prototype.

**Comment by dougwilson** [comment]
We have already moved out the http/2 work from express 5. And I know it was already brought up that we probably don't want to add so many breaking changes here that folks will just not upgrade. On that line, that would seem like an unnecessary breaking change though. One that users would have to do to move off 4 which is what we want, but they wouldn't actually gain any feature from doing so...

**Comment by LinusU** [comment]
> [...] brought up that we probably don't want to add so many breaking changes here that folks will just not upgrade. 

Good point 👍 

> On that line, that would seem like an unnecessary breaking change though.

Just to clarify, are we talking about the req/res extraction, or the mime-type switch?

I'd be happy to drop the mime-type things if we don't want them in just yet 👌

**Comment by dougwilson** [comment]
> Just to clarify, are we talking about the req/res extraction, or the mime-type switch?

I am talking about the former, but the latter is also open for discussion. The only "set in stone" breaking changes that come to my mind are the path to regexp (desperately needed) and undefined status (requested numerous times and it only breaks strange edge cases).

Others getting in can happen, not saying no of course, but if we find it delaying the others, or a larger thing than we thought we should make sure we really want to delay, lol.

The path to regexp is done enough where everythinf should be all merged up and out this weekend. And if we can land the last of breaking changes within then it'll be a RC, otherwise a beta to sweep in the last breaking this over next week or whatever.

That is my thoughts, at least :laughing:

**Comment by gireeshpunathil** [comment]
IIRC, re: req/res extraction change being included in 5:

pro: good to go with other breaking changes, or else we will have to wait till 6, which may be an year or more from now
con: more change in 5, more work to do

I guess @wesleytodd said he will be able to develop, test, land and publish in 2 week's time. If so, I am leaning towards that option, but would be good to know if there are other considerations than I quoted above?

**Comment by dougwilson** [comment]
I would like to get breaking changes completed by this weekend so we can publish an RC instead of a beta version. I believe @gireeshpunathil that was something you were championing before? To move on and not start like a beta cycle? If we're not doing with breaking changes I can't actually publish it as an RC, it would be another alpha or a beta.

The other consideration I had also came fro. your feedback of having too many breaking changes piled in to the same release. This one seems more so as the breaking change it not enabling some new use case or feature, right? Seems that it would at this point be a breaking change for the sake of it, which seems weird to try and smoosh into 5 at this point.

There is the settings breaking change that actually seems useful compared to this, yet it seems odd this would be more important than the settings change?

**Comment by gireeshpunathil** [comment]
@dougwilson - thanks.

> This one seems more so as the breaking change it not enabling some new use case or feature, right?

> Seems that it would at this point be a breaking change for the sake of it, which seems weird to try and smoosh into 5 at this point.

> There is the settings breaking change that actually seems useful compared to this, yet it seems odd this would be more important than the settings change?

unfortunately, my experience in this project is insufficient to make an assertion in either way on these points. @wesleytodd - can you please pitch in and ratify with @dougwilson on this?


> I believe @gireeshpunathil that was something you were championing before? To move on and not start like a beta cycle?

Yes. I am still holding on to that; we should do what it takes to release RC -> GA, not alpha or beta

> The other consideration I had also came fro. your feedback of having too many breaking changes piled in to the same release.

Yes. For the wider interest of the ecosystem (to consume majors / migrate with less pain). But from the nature of the change in question, it is not necessarily a `definite` breaking change? only code that assumed internal code layout and depended on that will be affected?

In either way, I think this is something that can be sorted out quickly between you and @wesleytodd  , unless others have strong opinions!

**Comment by dougwilson** [comment]
> Yes. I am still holding on to that; we should do what it takes to release RC -> GA, not alpha or beta

Yea, and I have come to agree with you on that, as a way to get this out. The path to regexp giant breaking change is compete and just needs to be released. The sooner we can release for community to test, I think the smoother it will be. But that then means that we can delay the release of that for testing to wait for more of these other changes to land and then make a RC or not wait and release another alpha or a beta...

**Comment by gireeshpunathil** [comment]
Change default setting of query parser, deprecation in 4.x line - PR in place, https://github.com/expressjs/express/pull/4208 . Please review, and do the needful, thanks!

**Comment by ryhinchey** [comment]
Is there a recording of this meeting?

**Comment by wesleytodd** [comment]
I just sent the recording to @dougwilson.  The plan is to upload it to YT.  I will try to follow up on the rest of the stuff later, but I have some stuff to do today before I am OOO next week, so sorry for the delayed responses.

**Comment by jonchurch** [comment]
This might be silly, but couldn't we move req/res into their own modules, but then also export those modules from the `lib/response.js` `lib/request.js` files, while adding a deprecation message?

If the assumption is people are requiring deep into the lib, that should be enough to prevent breakage of specifically that behavior.

**Comment by gireeshpunathil** [comment]
just want to track the progress of items planned for this week:
 - extended query parser deprecation in 4.x lines: https://github.com/expressjs/express/pull/4208 raised, needs review + landing. owners pls!
 - 4.x (4.17.2 or 4.18?) release with the said deprecation in it. again, owners pls!
 - repo captians proposal PR: @wesleytodd  seems to be OOO, I will attempt a PR soon.
 - given @wesleytodd  is OOO this week, decide on what to do with https://github.com/expressjs/express/issues/2432
 - https://github.com/expressjs/express/pull/3621 - land as is (given the peer PR https://github.com/expressjs/express/pull/4208 in place), or re-PR?
 - @jonchurch  's 5 items : where do we stand?
 - https://github.com/pillarjs/router/pull/42: according to @dougwilson , it just needs re-branching and merging. @dougwilson  - are you planning to do that?
 - https://github.com/expressjs/expressjs.com/pull/1114 : needs review + landing. owners pls!

at this point I would like to know the list of existing repo owners and committers for the relevant items above, so that I can individually follow up with them too.

thanks!

**Comment by gireeshpunathil** [comment]
repo captain proposal : https://github.com/expressjs/express/pull/4210 , pls review!

**Comment by dougwilson** [comment]
> at this point I would like to know the list of existing repo owners and committers for the relevant items above, so that I can individually follow up with them too.

Please, as I specificly asked above in https://github.com/expressjs/discussions//106#issuecomment-595345208 move this  conversation to #98 since it has a dedicated issue so we can discuss it without things getting lost. This issue is already a bit unwieldy with the number of different things all being discussed in the same thread.

**Comment by wesleytodd** [comment]
I have not read everything, but the list I posted above was volunteers as repo captians.  We would still want to ratify the proposed governance changes and vote on the proposed people (as per the process).

Also, agree this issue covers too much now.  We should probably split it out into a few.

**Comment by gireeshpunathil** [comment]
I opened #100 for specifically tracking express 5.0 release, for some reason discussions happen at the TC meeting tracker. I am going to cross-post the heavy-weight comment above, to #100

**Comment by gireeshpunathil** [comment]
closing this as:
 - purpose is solved, meeting happend,
 - actions identified, and are being tracked separately
 - keeping it open may (inadvertently) invite comments that are contextual but needs to be actually tracked elsewhere

please re-open if I am wrong here!
