### ISSUE TITLE
drop node v0.8 support

### ISSUE THREAD

**Issue by jonathanong** [expressjs/discussions#11]
@dougwilson knows that i struggle with it. i personally want there to be less maintenance overall. a lot of @dougwilson's time is updating modules. it probably annoys me more than him :)

seems like npm either doesn't care about 0.8 anymore and/or doesn't support it: https://twitter.com/seldo/status/712386414902521861

i believe the only blocker is express@5, correct @dougwilson?

**Comment by dougwilson** [comment]
Blocker for express 5? Express 4 doesn't even support node.js 0.8. I'm not sure what the connection is to 0.8?

There are lots of modules in the orgs that support 0.8 and imo dropping a version is a major version bump. If we are proposing new majors in modules, I think we can propose moving support to only 0.10 with that bump.

Personally I have to still use 0.10 for at least through this year, and I like to support as much as feasible because there are people in the same situation. I even had to add back 0.6 support to the node MySQL module after popular demand.

**Comment by jonathanong** [comment]
Oh shoot I thought express used 0.8.

Ok I'm fine with major version bumps. Npm stated only 0.04% of people are using 0.8.

A lot of people are using 0.10 so I don't see dropping that for at least 2 years

**Comment by tomByrer** [comment]
> A lot of people are using 0.10 so I don't see dropping that for at least 2 years

Meteor is using 0.10, but will [switch soon](https://github.com/meteor/meteor/issues/5124).  Ghost is compat with newer versions already.  But Node IIRC will drop v0.10 support Oct2016.

**Comment by jonathanong** [comment]
would be nice to drop support for both 0.8 and 0.10 at the same time. but i believe a lot of people are still using 0.10 =/

**Comment by jonathanong** [comment]
need to check the npm's latest graphs

**Comment by jonathanong** [comment]
https://docs.google.com/spreadsheets/d/1J6TxXIfGOqV9cx1qEFGSXHCma4JHfKPzlsMWfbGmDbE/edit#gid=0

**Comment by jdalton** [comment]
@jonathanong Who maintains the spreadsheet?

**Comment by jonathanong** [comment]
Laurie of npm I think

**Comment by gireeshpunathil** [comment]
is there anything outstanding here?

**Comment by dougwilson** [comment]
No, this is stale and has been superseded.
