### ISSUE TITLE
self-nomination for express committer

### ISSUE THREAD

**Issue by gireeshpunathil** [expressjs/discussions#113]
Non-trivial contributions:
 - PRs: https://github.com/pulls?q=is%3Apr+author%3Agireeshpunathil+org%3Aexpressjs
 - Involves (issues, triages, PR reviews): https://github.com/issues?q=involves%3Agireeshpunathil+org%3Aexpressjs
 - Helped defining a triage process and onboarding 10+ triagers: https://github.com/expressjs/discussions/issues/92
 - Help driving express 5.0 efforts: https://github.com/expressjs/discussions/issues/100
 - Help driving express evangelism, adoption and user experience: https://github.com/expressjs/discussions/issues/102

**Comment by dougwilson** [comment]
Thanks @gireeshpunathil for opening this issue. I hope that in our meeting the discussion around this and the expectations for the next steps you need to take are clear on what you need to continue to do in order to be elevated to a committer :+1: 

You have done a lot of work, and we are very thankful, but I do not believe there have been non trivial contributions at this time. A good example is on your recent PR in which it took quite some time in order to make a functional PR and it seems in general there is a lack of understanding of the underlying mechanisms of the documented commit process itself.

I think you are on the right path and we will reconsider as we see non trival contributions coming that do not require hand holding in order to get committer rights.

If you disagree, please expand on here. I did try and look though the list you provided, but there are quite a few in thee (like https://github.com/expressjs/session/pull/737) where it is unclear on what your contribution was (let alone it being non trival). You can also expand on what your plan is to do with the elevated status.

**Comment by gireeshpunathil** [comment]
@dougwilson - thanks for the feedback. Just expanding on a couple:

> where it is unclear on what your contribution was 

https://github.com/expressjs/session/pull/737 : came in 10 days ago and not tagged with any priority, so definitely not planning to look at it at the moment. After the GA, I have a mind to re-prioritize my work and start focussing on session repo 

> You can also expand on what your plan is to do with the elevated status.
 - work with peers / TC to identity priorities for the project
 - work with peers / TC to identify specific repos to focus
 - start picking up loads where existing bandwidth is scarce
 - identify improvement areas and come up with actionable plans
 - take part, and feel pride in the success of express!

**Comment by dougwilson** [comment]
I haven't heard anyone else weigh in on this, and with a comment like https://github.com/expressjs/session/pull/707#issuecomment-615014068 I think there is quite a road we need to work on here, and we can reassess such a request in the future.

**Comment by IamLizu** [comment]
I was reading some old threads and stumbled upon this. Closing in reference with https://github.com/expressjs/discussions/issues/227#issuecomment-2058128267.
