### ISSUE TITLE
Different destructuring behavior for req object for NodeJS version 16 and 14. 

### ISSUE THREAD

**Issue by sakib-87** [expressjs/discussions#157]
[For this code](https://runkit.com/sakib-87/express-request-headers-destructuring). If runs with node-14 and older got the headers object but If runs with node-16 and newer don't get the headers object.

**Comment by dougwilson** [comment]
Hi @sakib-87 sorry for your trouble. This change was made in Node.js itself, rather than Express.js. This is why you are seeing the difference depending on the Node.js version you are using, rather than the Express.js version. The `req` object is that from Node.js itself, just with helpers added by Express.js. The behavior is outside the control of Express.js.
