### ISSUE TITLE
Recurring TC Meeting

### ISSUE THREAD

**Issue by sheplu** [expressjs/discussions#195]
Following the last TC meeting, I think it is important - and it was quickly discussed (https://github.com/expressjs/discussions/issues/161#issuecomment-1947594232) - to setup a recurring meeting for the TC.

I am suggesting to follow the same schedule as other organization, so one meeting every two weeks, with an alternating timeslot as the TC is divided between Europe and USA.

As the TC meeting is live - and maybe be joined by contributors or spectators I am opening this issue to try to find the best time and to validate the schedule

Suggestion
- one meeting every two weeks
- alternating schedule every 2 weeks between US timezone and European timezone
- Setup automation if possible
- Keep tracts of all minutes 
- Setup live youtube and recording (zoom?)

If all the @expressjs/express-tc is on board with that, I will open a doodle with multiple slots so we can choose what would be the two best time

**Comment by dougwilson** [comment]
Interesting proposal. It would be interesting to know who would attend each one, as if one of them does not actually have a majority of the TC members in it, it would seem no decisions could actually be made within that TC meeting, so it could only end up being a stand up of sorts without prediscussions and input from the non attendites before hand or delay the decisions to do the same after the fact to get majority.

**Comment by sheplu** [comment]
For me we should find time to have all the members, but with a 9h gap between US / Europe we can find some time that would not be at a desavantage for one side and alternate between a good time for the people in the US and a good time for the people in Europe.

Last meeting was at 1am for me, and that's not an issue if it is not too often. That way it would be only one meeting per month with a non optimal time for all (at worst)

**Comment by dougwilson** [comment]
No ya, I get it. It is certainly something to consider when wqnting to join the TC. My comment was just that whatever we do, we would probably need to decide (1) will both meetings actually regularly have a majority of the TC in order to actually make any decisions in it and (2) does missing one in your non time zone count against you for TC removal (it is currently codified thay it will -- so missing one meeting in your own time zone and not going to the other time time would then remove you from the TC).

**Comment by sheplu** [comment]
For me this would not change the rule, this is just a way to alternate the meeting between two schedules (and not have two meetings at the same time).
It would be
- week 1: slot 1
- week 2: nothing
- week 3: slot 2
- week 4: nothing
And then we circle on that

But we can also have the meeting at the same slot, but anyway we need to find a good schedule - and maybe this is the one we used last time.
But at least we should validate that, and setup / schedule everything

**Comment by wesleytodd** [comment]
Yeah this is exactly my worry, with a larger TC it becomes easier to not have one meeting be a ghost town and the other be the only one which can reach quorum. For now, we are going to likely have to make some compromises to keep things going. If we think the scheduling might cause an otherwise active member to miss more of the TC meetings that was in our governance doc update, I say we change the doc to have looser requirements.

One other thing to keep in mind is the meeting itself is more just a way to unblock things and talk in person. The voting aspect is strictly if we cannot find a good compromise, so maybe we just say that any meeting with a vote called also needs a way for members who could not attend to vote remotely after (or before)?

**Comment by UlisesGascon** [comment]
> For now, we are going to likely have to make some compromises to keep things going [...] One other thing to keep in mind is the meeting itself is more just a way to unblock things and talk in person

I Agree, the key of this meeting is to unblock things and solve things that are more complex offline. As the TC has just being reactivated, we need sometime to grease the wheels as a team and define our way of collaborating and working together.

Obviously this scenario can't be sustain over a long period of time, but we can try to keep one single session until we feel confident to split. I guess that there are some stuff to polish before that like meeting minutes, agenda, etc.. so it is easier to follow up and also how we make complex decisions as group that require voting, etc... 

IMO, I think that voting to solve disputes should be conducted offline, because:
- We don't need to wait for the 2w circle
- We let more time to present ideas, convince others and personal research on the topics

**Comment by dougwilson** [comment]
Re the voting: I think the concern that the voting is ideally supposed to be a last resort that we only need to do rarely. But my concern is if there are regularly TC meetings without a majority of TC there due to them being split, simple consensus cannot be achieved and we would have to restort to voting on the regular to make decisions instead.

**Comment by wesleytodd** [comment]
I think ideally we can reach consensus in issues. Frankly I think we should really strive for no votes being necessary as it has been historically. That said, we should not avoid it if something is in fact blocked and in that case I would hope we can just agree to find a time which enables meeting quroum (even if that needs an ad-hoc meeting) or just vote via an issue and record it during a meeting for the records keeping.

**Comment by sheplu** [comment]
I agree with most of the points about voting but the main idea behind this issue was mostly to have a regular meeting, with an agenda and critical topics to discuss.
Do we agree that we want to have a regular meeting with the TC, like most WG operate? If yes
- when? Same time as the previous one?
- which regularity?

**Comment by UlisesGascon** [comment]
> Every other week? 
 
 I think that will work fine, regarding the best time. Maybe we can do a new doodle but oriented to regular slots (Monday to Friday?) and we can alternate between the two most popular slots. That way we cover a larger spectrum. Maybe I am overengineering this? 🤔

**Comment by wesleytodd** [comment]
> Maybe I am overengineering this?

No, scheduling is harder than any of the software engineering we do.

> Maybe we can do a new doodle but oriented to regular slots (Monday to Friday?) and we can alternate between the two most popular slots.

I think this is a great plan, whoever gets to it first can post the link here!

**Comment by sheplu** [comment]
here is the link with all slots. let's try to find two alternating slot if possible (the two with the most vote)
https://doodle.com/meeting/participate/id/b4WoLRga

**Comment by jonchurch** [comment]
There is language currently around TC attendance to maintain active status. I doubt we are in danger territory of pushing any currently active members out bc of that. 

However, maintaining scope of commitment is important when it comes to membership w/r/t required hours in meetings. And changing that scope of commitment underneath someone is dangerous, gets into "I didnt sign up for this" territory. 

What is yalls opinion of increasing cadence and the expectation to attend all meetings? I can see how the expectations of the TC may have shifted with the flurry of activity. But they have not shifted officially as per the current governance. 

Aka, is the TC comfortable with an increased meeting cadence becoming the expected level of commitment for TC members rn? Absence to which meetings count towards "inactive" status. Sorry for getting hypothetical, but one way to weaponize this would be to have TC meetings changed to every 3 hours, and then just wait 18 hours for absent members to accrue 6 absences and unilaterally remove them from the TC. 

A solution is to distinguish between "official monthly" meetings and more frequent working sessions. Then clarify the absence policy refers to 6 official monthly meetings. 

(i have read more board of directors bylaws then I care to admit)

**Comment by wesleytodd** [comment]
@jonchurch what do you think about this? https://github.com/expressjs/express/pull/5510

I agree completely and am worried maybe the original wording was too restrictive.

**Comment by jonchurch** [comment]
The original wording is fine in a world where there is 1 official meeting per month and it is at a set time that people can plan around. However I don't think that is specified in the current documents. Other organizations typically have bylaws that specify one monthly official meeting with mandates for how long notice must be given prior to convening an official meeting, and then providing for ad hoc cadences of working sessions/committees etc. It creates a floor of commitment, but leaves the ceiling wide open.

leaving comments on the PR directly, tho

**Comment by jonchurch** [comment]
Robin Ginn of openjsf pointed me to Nativescript, who templated their governance off of node's. Heres the start of the relevant TSC section, a section about meeting cadence follows

https://github.com/NativeScript/management/blob/master/nativescript-governance.md#technical-steering-committee-tsc

**Comment by sheplu** [comment]
Tagging the @expressjs/express-tc folks again :) 

I think we can validate a first schedule tomorrow end of day, and then have a first meeting next week to have the thing started. If it is not perfect we can see to move it.

**Comment by sheplu** [comment]
So we have two winners :) 
- week 1: Monday 10pm Paris time (GMT+1)
- week 2: Wednesday 10pm Paris time (GMT+1)

This is the only two with 5 votes. Are we good to start with that ?
@expressjs/express-tc @wesleytodd @UlisesGascon @jonchurch @crandmck 

Wes: How can we setup the meeting, do we have a zoom account / youtube setup?

**Comment by wesleytodd** [comment]
Works for me!

> Wes: How can we setup the meeting, do we have a zoom account / youtube setup?

Yeah I have both. [I landed a PR on meet](https://github.com/pkgjs/meet/pull/145) which I was intending to try out to setup the agenda. I think ideally we add it on the OpenJS calendar (I will reach out to Ben if we agree on this to set it up) which would give us the zoom link I think.

**Comment by wesleytodd** [comment]
I think I got this working: https://github.com/expressjs/discussions/pull/206

We probably want to pick a better label for longer term, but I used the `top priority` one for now so that we don't have a missive list of issue while we get started.

**Comment by UlisesGascon** [comment]
> I suggest that we start "this" Monday, so Monday 4th

Works for me! 👍

**Comment by sheplu** [comment]
I think we could use the label `xxx-agenda` for all the WG, including the TC?
- tc-agenda
- security-agenda
...

**Comment by wesleytodd** [comment]
Agreed! I only used that label as it already existed and I had limited time. I will look at a fix to remove duplicates and then update it to a new label ASAP so it can create next weeks meeting.

**Comment by wesleytodd** [comment]
Ok, I updated to remove dupes: https://github.com/pkgjs/meet/pull/202

I am also updated this with the schedule: https://github.com/expressjs/discussions/pull/206

I am going to close this and follow up with that PR where I will also change the agenda label.
