### ISSUE TITLE
TC Meeting for 7/8/2016?  Also, Minutes Doc?

### ISSUE THREAD

**Issue by cdnadmin** [expressjs/discussions#23]
Was wondering if there was a TC meeting for 7/8/2016? I didn't find an issue for that date.  

Also, was wondering if it would be possible to have the minutes in a doc (e.g. google doc) to have something to quickly scan over, in lieu of watching the recording--which we'd still keep.

**Comment by crandmck** [comment]
TC meetings are held every other Weds. There was a meeting last Weds, and the next meeting will be 15 July at [23:30 UTC ](https://www.google.com/search?q=23%3A30+UTC&oq=23%3A30+UTC).

> Also, was wondering if it would be possible to have the minutes ...

We've gotten a bit lazy about keeping minutes, but I'll try to start doing it again.  I think posting them as a comment in the issue for the meeting would be a good place (rather than a separate doc).  I took a few notes at the last meeting, but I can't seem to find them now.  
@dougwilson @blakeembrey @LinusU @hacksparrow Did you take any notes?

I've also been meaning to put some info about TC meetings in http://expressjs.com/en/resources/community.html and/or http://expressjs.com/en/resources/contributing.html as well as links to the meeting minutes.  I'll open an issue to remind me to do that.

**Comment by cdnadmin** [comment]
Thx, @crandmck hadn't realized they were every other week.  sorry.  😜 i think i was going by Node's weekly.  

also, thx for the minutes notes.  notes in either conversation or doc is good, as long as we have something I think would be good.   👍
