### ISSUE TITLE
Should we keep the object prototype in req.body and similar fields

### ISSUE THREAD

**Issue by LinusU** [expressjs/discussions#25]
This question and similar comes up now and again: https://github.com/expressjs/multer/pull/318

I'm not really sure what to do, maybe we could discuss this on the next TC meeting.

On the one hand

> Consider what would happen if the client sent hasOwnProperty=nope or hasOwnProperty[call]=. This would break any script trying to use req.body.hasOwnProperty(_), and having client data break server code is never good.

On the other hand we get a few request from time to time and often they are using some utility library that breaks.

I think the main point would be to be consistent throughout our packages. It seems like most packages parses the body with the prototype intact.

> While I can respect the cautiousness taken in the design, I believe this is one time where it's better to be consistent as a community, regardless of whether that is right or wrong. Currently, all of bodyparser's parsers spit out an `Object` object:

> - [urlencoded](https://github.com/expressjs/body-parser/blob/master/lib/types/urlencoded.js#L84)
> - [json](https://github.com/expressjs/body-parser/blob/master/lib/types/json.js#L96)
> - [raw](https://github.com/expressjs/body-parser/blob/master/lib/types/raw.js#L60)
> - [text](https://github.com/expressjs/body-parser/blob/master/lib/types/text.js#L62)

**Comment by blakeembrey** [comment]
I think using prototype-less objects is definitely better and it avoid having odd gotchas in people's code as handling it would need to be done consistently (E.g. it either exists or it doesn't, it's not maybe a function, maybe something the user passed). That said, it's tricky because a lot of people do rely on it. With the introduction of node 6 setting the precedent (removing the object prototype from headers), I think more people should and will be writing prototype-less objects for user input. Native methods like `JSON.parse` may be an issue though, so we need to figure out how to handle that - maybe we can move to `Object.setPrototypeOf` (with polyfill?).

**Comment by blakeembrey** [comment]
Also, FWIW, `urlencoded` will also have a `null` prototype in node 6 since they patched that with the headers. So technically that comment is incorrect, which just means we should be making it the most common denominator already (https://github.com/nodejs/node/blob/master/lib/querystring.js#L8-L12).

**Comment by dougwilson** [comment]
I am in general undecided on this. I personally lean more towards a `null` prototype, since it more accurately describes the type of object, but at the same time, it's actually pretty hard to interact with those types of objects in some cases. I feel like the main argument for the `null` prototype is to just to get developers to not even be able to make a dumb mistake when initially writing the code, but IDK

**Comment by LinusU** [comment]
This aws discussed at the [Express TC Meeting 2016-08-10](https://github.com/expressjs/discussions/issues/29) and the consensus was to keep the prototype as `null`.
