### ISSUE TITLE
Translated Readmes

### ISSUE THREAD

**Issue by LinusU** [expressjs/discussions#38]
Would like to raise something that I ran into today. Multer got a pull request with a translation of the readme into Chinese. I think this is great, but I don't have any good ideas for making sure that the translation is kept up to date. Maybe this is a non-issue though, would love some input from some other maintainers. Thanks ❤️ 

Pull request: expressjs/multer#400

**Comment by dougwilson** [comment]
Yea, it's really hard. The only experience I've had was with the understanding csrf thing, and it's not great. The best case is people from the other language periodically making PRs to match English changes, and the worst case is issues complaining it's out of date and asking for you to update it.

Things like google translate exist, and I would say that other languages can use that, but I'm not sure how good it is :)

**Comment by crandmck** [comment]
This is something that tech writers grapple with all the time.  In general, since we constantly update and improve the documentation in English, translated content will inevitably get out of date.  If you have a translation budget and work with professional translators, it's pretty straightforward to do incremental translations to keep them up to date with changes in English content.

For open source community translation, though, it's another matter. It's typical in my experience to put a prominent disclaimer at the top of every such page that states it's a community translation that may not be up to date with the latest English content, and the reader should always refer to the English version for the latest and most accurate information (with link).

We've even done this for the professional translations that IBM provided of the Express docs.  
For example: http://expressjs.com/de/

So, AFAIK, this is about as good as we can do.  It's either that or just don't accept community translations, which of course excludes non-English speakers.  I guess you could argue it either way, but in my view _something_ is better than nothing.

As far as machine translation (e.g. Google Translate), I believe it's getting better, but unfortunately it's still not that good.  It does OK for one or two simple sentences, but beyond that, the inaccuracies add up to the point where it can become more dangerous than valuable--by that, I mean that small differences in translation can completely change the meaning; or be so very difficult to decipher.  It may have some value, but in the end the reader is left trying to sort out a puzzle.  I've discussed this at some length with some of the globalization experts at IBM, and they don't have a great deal of confidence in it (yet).

**Comment by dougwilson** [comment]
Thanks for your insights, @crandmck , very enlightening!

**Comment by LinusU** [comment]
My notes from the last meeting:

We will go ahead and merge the pull request. The current structure is that translations are put in a `doc` folder with the language code in the name, like so: `doc/README-zh-cn.md`.

All languages are linked from the top of each file, like so:

**README.md**
```md
## Language
English [简体中文](./doc/README-zh-cn.md)
```

**doc/README-zh-cn.md**
```md
## Language
[English](../README.md) 简体中文
```

**Comment by crandmck** [comment]
Sorry I didn't catch this before.... The entry in the main README.md is confusing.  Why does it say "English" when it's a link to the Chinese README?  I'll open a PR with my suggested modification.
